### ISSUE TITLE
Site not working offline

### ISSUE THREAD

**Issue by djcaesar9114** [le4ker/personal-jekyll-theme#189]
## Questions

When I deploy the website on a machine not connected to the internet, or when I want to work offline on the website, some things don't work, as bootstrap.
## Expected Behavior

I'd like to be able to see the same result on an offline machine as on a connected one.
Why not include a minified bootstrap in the repo? 
## Actual Behavior

Element misplaced in the navigator.
## Steps to Reproduce the Issue
1. disconnect your machine from the internet
2.  `jekyll serve`
3. open the website
## Specifications

It doesn't depend on the computer, actually.

**Comment by PanosSakkos** [comment]
The reason that bootstrap (i.e.) is served from the cdn is that @joariasl believed that it's more efficient than serving the minified versions from the { Personal } server. Personally I would be interested into running a few tests with and without the cdn and comparing those before making a decision on it 😄
