### ISSUE TITLE
Images resizing not correct

### ISSUE THREAD

**Issue by djcaesar9114** [le4ker/personal-jekyll-theme#193]
## Expected Behavior

When I put images in the timeline, I'd like to see them resized to fit the circles.
## Actual Behavior

If the images are not sized well enough, you see ellipsoidal images too much inside the circles or too much outside.
## Steps to Reproduce the Issue
1. Put new images in the `/img/timeline/` folder
2. Change `_config.yml`
3. `jekyll serve`
4. Display the timeline
## Specifications

Every version of the browser, with { Personal } up to date

**Comment by djcaesar9114** [comment]
I've got two ways to solve this issue:
1. The easy one: modifying the CSS so that the image fits whatever the original dimensions are. You can set the images of the timeline with these properties:
```
width: 100%;
height: 100%;
```
2. Creating a "generate timeline images" script which resizes the images correctly, why not creating new images, "image.png" giving "timeline_image.png".

I'll work on this issue, so I'm open to any comment.

**Comment by PanosSakkos** [comment]
The images should be square in order to be rendered correctly, but I like that you're trying to tackle that problem. Did you come up with a good enough solution?
