### ISSUE TITLE
Add static text to prefix typed text.

### ISSUE THREAD

**Issue by dotps1** [le4ker/personal-jekyll-theme#216]
## Questions

I would like to prefix my typed text so it looks static, like im entering a command in the shell.  My site is targeted at PowerShell, so my typed text is powershell commands, it would be cool to have a static `PS C:\> ` so it looked like the text was typed at a shell prompt.

https://dotps1.github.io

## Steps to Reproduce the Issue

  1.
  2.
  3.

## Specifications

(The version of the project, browser etc.)

**Comment by eiselems** [comment]
I would have provided a fix but yet I am not very happy with the look of the outcome because of css.
It does not look like a proper shell.
Maybe https://github.com/le4ker/personal-jekyll-theme/compare/master...eiselems:staticTyped can help you with a quick and dirty fix to get you started.
