### ISSUE TITLE
Highlight codeblocks

### ISSUE THREAD

**Issue by dotps1** [le4ker/personal-jekyll-theme#218]
## Questions

code block in closed in triple back ticks can not be highlighted, this is not a good feature, as it most likely will be copy and pasted by the reader.

## Expected Behavior
should be able to highlight and copy and paste code from withing code blocks.

## Actual Behavior
this cannot be done.

## Steps to Reproduce the Issue

  1.
  2.
  3.

## Specifications

(The version of the project, browser etc.)

**Comment by cdrrazan** [comment]
Which codeblocking syntax or component will help for this theme? :-1:
