### ISSUE TITLE
Public Docker image for use Personal-jekyll-theme

### ISSUE THREAD

**Issue by joariasl** [le4ker/personal-jekyll-theme#219]
## Expected Behavior
A Docker image for develop and deploy Personal-jekyll-theme without require install tools in the system.

## Actual Behavior
Installation of tools are required for develop and deploy Personal-jekyll-theme. This cause problems when any version of tool required or installed in the system is deprecated, updated or not supported.

## Specifications
* Create or document the use of a Docker image for Personal-jekyll-theme.

**Comment by le4ker** [comment]
That's an awesome idea! 👍

**Comment by le4ker** [comment]
I deployed { Personal } on a dedicated vanilla machine with Ubuntu and as far as remember I needed Apache, ruby with the { Personal } dependencies and ftp :smile:

**Comment by joariasl** [comment]
I am an expert in Docker and tools, so I will contribute some time to close this issue in a few more days. 😄

**Comment by eiselems** [comment]
This so much, think this is a real hurdle to pass if you want to contribute.
Just make sure it is well documented in the Readme.

**Comment by joariasl** [comment]
Command for run with Docker:
`docker run --rm -it -p 4000:4000 -v "$PWD:/srv/jekyll" jekyll/jekyll /bin/bash -c 'PATH=$PATH:/srv/jekyll/scripts; /bin/bash'`

**Comment by le4ker** [comment]
@joariasl can you create a docker-compose file with this commands? 😄

**Comment by joariasl** [comment]
It's done few days ago: 712f71c7e5255db86f3a4f2c65dac0a98ba429c8

:)

**Comment by eiselems** [comment]
@joariasl just used it with docker compose - works really like a charm. Great work there!

**Comment by le4ker** [comment]
Great stuff! 😄 👏
