### ISSUE TITLE
Link in Repo Header doesn't work any more

### ISSUE THREAD

**Issue by siboehm** [le4ker/personal-jekyll-theme#220]
@le4ker You changed your name but forgot to change the link to the static github page in the repo header, it still links to panossakos.github.io instead of le4ker.github.io which doesn't work anymore.

**Comment by le4ker** [comment]
Fixed :+1: thanks for reporting it!

**Comment by siboehm** [comment]
The Repo Description still has the wrong link

**Comment by eiselems** [comment]
![bildschirmfoto 2017-08-26 um 23 47 04](https://user-images.githubusercontent.com/5188694/29745369-23adab7e-8ab9-11e7-8573-98f9c6db9395.png)

**Comment by joariasl** [comment]
@le4ker it's not fixed yet!

**Comment by joariasl** [comment]
The same problem is in all old content:

1. Example images in the README.md.
2. Link in promotional Web Pages. (http://jekyllthemes.org/themes/personal/)
3. Setup documentation for example: https://le4ker.github.io/personal-jekyll-theme/tech/2015/06/25/initial-setup.html

**Comment by le4ker** [comment]
Good catches everyone! I fixed the references that you mentioned and I opened a [PR](https://github.com/mattvh/jekyllthemes/pull/530) on jekyll themes.
