### ISSUE TITLE
Added designed.html

### ISSUE THREAD

**Issue by aditya81070** [le4ker/personal-jekyll-theme#225]
I tried to add an html file  named designed.html after copying this repo to my personal repo aditya81070.github.io.
It displays all the content of html file  but it is not detecting images from my repository.
please help me in this matter.
I am a rookie in field of web developing and know only basic html.

**Comment by le4ker** [comment]
Hello @aditya81070 , please ask your question on our [gitter](https://gitter.im/PanosSakkos/personal-jekyll-theme) 😄
