### ISSUE TITLE
How to use this theme in Hosting sites ?

### ISSUE THREAD

**Issue by HimanshuChandolaa** [le4ker/personal-jekyll-theme#231]
Sir i have bought paid hosting for 1 year... I uploaded all files in public html folder but when i am refreshing website nothing is shown up....... How to use this theme in cpanel based web hosting ?

**Comment by ThomasVdBerge** [comment]
You'll have to build it and upload the builded files

**Comment by eiselems** [comment]
1. You have to use one of the ways to generate your sites (locally, our using docker / docker-compose).
2. When you have done that you just have to upload the /_site folder to your public html folder. It contains an index.html and every other generated asset.
