### ISSUE TITLE
I need help adding a portfolio page

### ISSUE THREAD

**Issue by stephenajulu** [le4ker/personal-jekyll-theme#238]
## Questions

Hey how are you? I have been trying to add a portfolio section to my page but to no avail. I am a noob and just starting to learn about jekyll and liquid tags. So far so good i have been able to add and remove a few things. But now i need a portfolio section in the page. Where i can display my 3 latest works. just after or before the timeline.

You can view the site [here](https://stephenajulu.github.io)!
Your help will be appreciated

**Comment by joariasl** [comment]
Hi.
First, you need to declare the existence of the page in the wanted position in the line https://github.com/le4ker/personal-jekyll-theme/blob/bbe99000ceb9f9fc96a0576792c92596971690f0/_config.yml#L198
This will be add the include of the page files from the declaration https://github.com/le4ker/personal-jekyll-theme/blob/bbe99000ceb9f9fc96a0576792c92596971690f0/_layouts/index.html#L15
(`site.pages` is a list of all pages https://jekyllrb.com/docs/variables/)

Second, you need to create the page content and add their metadata like https://github.com/le4ker/personal-jekyll-theme/blob/master/about.html

Third, you have to make the template to your new content like https://github.com/le4ker/personal-jekyll-theme/blob/master/_includes/about.html

If I remember all correctly, now you can be able to add a new page content to the home page.

Good lock.

**Comment by stephenajulu** [comment]
Thank you very much. I will update you on the progress.

**Comment by stephenajulu** [comment]
it didnt work @joariasl 
kindly take a look and advise me: [Portfolio include](https://github.com/stephenajulu/stephenajulu.github.io/blob/master/_includes/portfolio.html)

**Comment by joariasl** [comment]
You have bad syntaxis, you have to make your `_includes/portfolio.html` like the `_includes/about.html` file.

**Comment by stephenajulu** [comment]
[The problem is here](https://github.com/stephenajulu/stephenajulu.github.io/blob/master/_includes/portfolio.html)
I need help. I want it to appear in the home page in a cleaner style. This is how the portfolio section looks like. Had to resize one of the pics. But that's not what i want. I want it to be automatically resized in the homepage portfolio section but in 1080p in the page itself. I serioulsy need help with this tried a couple of code but nothing happened. i even had to specify the image size. but still to no avail.
![Annotation 2019-08-01 205751](https://user-images.githubusercontent.com/42298053/62315996-38f6aa00-b49f-11e9-9d32-4db0038582ba.png)

**Comment by stephenajulu** [comment]
@joariasl Your help will be appreciated.

**Comment by joariasl** [comment]
You have to remove the global `a` element and make your own CSS rules according to the site style, removing the `panel*` classes in your divs.

**Comment by stephenajulu** [comment]
thank you
