### ISSUE TITLE
GitHub Pages failed to build your site.

### ISSUE THREAD

**Issue by lh1008** [le4ker/personal-jekyll-theme#245]
## Questions

Please ask your questions at the [gitter channel](https://gitter.im/PanosSakkos/personal-jekyll-theme).
That way the issues here are kept clean and you will get an answer to your question quicker :smile:

## Actual Behavior

Got this error:

A file was included in /_layouts/index.html that is a symlink or does not exist in your _includes directory.

## Steps to Reproduce the Issue

  1.
  2.
  3.

## Specifications

(The version of the project, browser etc.)

**Comment by eiselems** [comment]
Could you please give the steps to reproduce?

Guess it is;

Forking and publishing. I will try it for myself in the upcoming days. Did you change anything else to encounter the issue?
