### ISSUE TITLE
Background image doesn't work

### ISSUE THREAD

**Issue by cesar-lizurey** [le4ker/personal-jekyll-theme#259]
Hello,
I was checking on the latest version of your theme and I saw the background image didn't appear anymore. Is that an intentional change or is it a bug? If so, I'm on it, I need it for my website (just so that you can take a look: https://cesar.lizurey.fr).
Have a nice day ;)

**Comment by le4ker** [comment]
I _think_ I removed it from the demo a few months ago. 

If you set an image now, does it work or is the functionality broken?

**Comment by cesar-lizurey** [comment]
I don't know, I refactored all the background CSS, I'll make a pull request because I think I made some improvements. You'll tell me ;)
