### ISSUE TITLE
Wrong position for gradient

### ISSUE THREAD

**Issue by djcaesar9114** [le4ker/personal-jekyll-theme#262]
Hello and first of all thank you for your work on 9.0.0!

I've just seen a problem with the CSS:

![image](https://github.com/user-attachments/assets/c94473b3-583c-4e48-8a44-db0fbc0d4daa)

Take a look here on a computer screen: https://le4ker.github.io/personal-jekyll-theme/

**Comment by le4ker** [comment]
@djcaesar9114 yeah it's a bug. Do you know how to fix it? My CSS skill are not great 😅

**Comment by cesar-lizurey** [comment]
> @djcaesar9114 yeah it's a bug. Do you know how to fix it? My CSS skill are not great 😅

Yes, that will be my Christmas present ^_^

**Comment by cesar-lizurey** [comment]
Done! https://github.com/le4ker/personal-jekyll-theme/pull/263
